export const ZONES = {
  all: {name:'全部区域',color:'#315b51'},
  transformers: {name:'变形金刚基地',color:'#426889',label:[39.85750,116.6747]},
  jurassic: {name:'侏罗纪世界',color:'#577b53',label:[39.85575,116.67665]},
  potter: {name:'哈利·波特的魔法世界',color:'#7d6397',label:[39.85620,116.68065]},
  panda: {name:'功夫熊猫盖世之地',color:'#ad6853',label:[39.8580,116.67755]},
  minions: {name:'小黄人乐园',color:'#b68c32',label:[39.8527,116.6787]},
  hollywood: {name:'好莱坞',color:'#ae7386',label:[39.8535,116.6748]},
  waterworld: {name:'未来水世界',color:'#538d95',label:[39.85830,116.67985]},
  other: {name:'其他 / 城市大道',color:'#778079'},
};
// 中文展示名、区域与体验时长为本地编辑资料；时长仅作可修改的行程估算。
const entries = [
 ['Decepticoaster','霸天虎过山车','transformers',5,'coaster',1],
 ['Transformers: Battle for the AllSpark','火种源争夺战','transformers',8,'sparkles',1],
 ['Bumblebee Boogie','大黄蜂回旋机','transformers',5,'orbit'],
 ['Transformers: More than Meets the Eye','变形金刚：传奇现场','transformers',15,'bot'],
 ['Jurassic World Adventure','侏罗纪世界大冒险','jurassic',10,'footprints',1],
 ['Jurassic Flyers','飞越侏罗纪','jurassic',6,'bird',1],
 ['Raptor Encounter','奇遇迅猛龙','jurassic',15,'footprints'],
 ['Camp Jurassic','侏罗纪营地','jurassic',20,'trees'],
 ['Aquilops Dolores Meet and Greet','小角龙桃乐丝见面会','jurassic',15,'footprints'],
 ['Baby Raptor','小迅猛龙见面会','jurassic',15,'footprints'],
 ['Harry Potter and the Forbidden Journey™','哈利·波特与禁忌之旅','potter',10,'wand-sparkles',1],
 ['Flight of the Hippogriff™','鹰马飞行','potter',5,'bird'],
 ['Ollivanders™','奥利凡德','potter',15,'wand-sparkles'],
 ['Frog Choir™','青蛙合唱团','potter',15,'music'],
 ['Triwizard Spirit Rally™','三强争霸赛动员会','potter',15,'flag'],
 ['Hogwarts™ Express Conductor','霍格沃茨特快列车长','potter',10,'train-front'],
 ['Nighttime Magic at Hogwarts™ Castle','霍格沃茨城堡夜间灯光秀','potter',15,'sparkles'],
 ['Hogwarts™ Always','霍格沃茨：永远','potter',15,'sparkles'],
 ['Kung Fu Panda Journey of the Dragon Warrior','功夫熊猫：神龙大侠之旅','panda',10,'waves',1],
 ['Lanterns of Legendary Legends','灯影传奇','panda',5,'lamp'],
 ['Carousel of Kung Fu Heroes','炫转武侠','panda',5,'orbit'],
 ['Kung Fu Games','功夫游戏','panda',15,'gamepad-2'],
 ["Po's Kung Fu Training Camp",'阿宝功夫训练营','panda',20,'swords'],
 ['Po Live','阿宝现场','panda',15,'star'],
 ['Peach Tree of Heavenly Wisdom','智慧仙桃树','panda',10,'trees'],
 ['Kung Fu Panda Meet and Greet','功夫熊猫见面会','panda',15,'camera'],
 ['Despicable Me Minion Mayhem','神偷奶爸小黄人闹翻天','minions',10,'glasses',1],
 ['Super Swirly','超萌漩漩涡','minions',5,'orbit'],
 ['Loop-Dee Doop-Dee','萌转过山车','minions',5,'coaster'],
 ['MINION GAMES','小黄人游戏','minions',15,'gamepad-2'],
 ['Minion Meet and Greet','小黄人见面会','minions',15,'camera'],
 ['Minions Cream Soda Show','小黄人泡泡秀','minions',15,'sparkles'],
 ['SING on Tour!','欢乐好声音巡演','minions',25,'music',1],
 ['Lights Camera Action!','灯光，摄像，开拍！','hollywood',20,'clapperboard',1],
 ['Untrainable','不可驯服','hollywood',25,'bird',1],
 ['Hollywood Meet and Greet','好莱坞明星见面会','hollywood',15,'camera'],
 ['Universal on Parade','环球大巡游','hollywood',30,'flag'],
 ["Universal's Halftime Show",'环球中场秀','hollywood',20,'music'],
 ['Universal Pop','环球流行音乐','hollywood',20,'music'],
 ['Minions & Monsters Character Meet and Greet: James and Henry','小黄人与怪兽：角色见面会','hollywood',15,'camera'],
 ['WaterWorld Stunt Show','未来水世界特技表演','waterworld',25,'waves',1],
 ['ONE PIECE - Straw Hat Crew Encounter','航海王：草帽一伙见面会','other',20,'flag'],
 ['Universal Cool Summer','环球酷爽夏日','other',20,'sun'],
 ['Universal CityWalk Cinema','环球城市大道电影院','other',120,'clapperboard'],
];
const catalog = Object.fromEntries(entries.map(([name,zh,zone,duration,icon,featured])=>[name,{zh,zone,duration,icon,featured:!!featured}]));
export function enrich(children,live) {
 const byId=new Map(live.map(x=>[x.id,x]));
 return children.filter(x=>Number.isFinite(x.location?.latitude)&&Number.isFinite(x.location?.longitude)).map(x=>({...x,...(catalog[x.name]??{zh:x.name,zone:'other',duration:15,icon:'map-pin',featured:false}),latlng:[x.location.latitude,x.location.longitude],live:byId.get(x.id)??{}}));
}
export const DEFAULT_NAMES=['Decepticoaster','Transformers: Battle for the AllSpark','Jurassic World Adventure','Harry Potter and the Forbidden Journey™','WaterWorld Stunt Show'];
